language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: l4m7hOr2nWmwSJnvY2eIelrVeEQURvC8Bt2pn6oXFUpBIW0ywZlh+zJSj/OCO/B3Al1/dgyos+AMmbfQ/OIfPglnQtuFyDla2ygfH05q2PXZ14w0CMGmx0T7tXlDXp2yAlAnm6gaiNMEOfs2iK7Jz2dGRuI1/Qc0WN4PFYRBUc9P+JZy6p4ThQaHnVpF2lF8tNKLmMCJ7YMPWGZvS9hkRNtYanV2jS37u5+h/B87ebOfncxnraI+t9XLD7S1SICgdO5UfU7KiNY5yhGKn4jUy3kbfjeq1YFJdFiaFw4FWGuT6gLsn8A9GcnXrFFsRES8ojXm/oeP5FVd/kGltjGvLDTiaNlrYBKss/Wu+pjjDx2RQ6GhTp4quyso8Xc4giAzltMb9vVNnk8sskReRLXrTUqcRKX4gvFfctwMB+o6LKQ1u1zg8aWSnlvU8tufevI7PeLix7nP3GBwde190vY3ixs5K41KsdgJlPukZN2nZjf/FdKlwAxcelcr9X41LO9ShDyo01Pdc/A/cryeT2ObbZoSbVp5dePHZR9NHUt308mLwc8EdwjsvZeZn+saNFWTY2jt4t8vCuIR5m75HBBCQQ26IgZoGhajeiXTSwshN3JY7d89Z2fmoayBNW+mQ1Dmc6M6ZIh23x4ceTe00rn+lpTr+yLR7YO9T9/o9ZUbLp4=
